name: Deploy Container image to aws ECR
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  aws_ecr_dockerfile_deploy:
    runs-on: ubuntu-latest
    name: AWS ecr deploy- A job that deploys a image container using a aws_ecr_dockerfile_deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy container image to AWS ECR
        uses: nyakaz73/aws-ecr-deploy@v0.08
        with:
          access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ${{ secrets.AWS_REGION }}
          aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
          image_name: web3hub
          use_compose: true

      - name: Get the output status
        run: echo "${{ steps.deploy.outputs.status }}"
